### ISSUE TITLE
Missing call to AddRef in QueryInterface ?

### ISSUE THREAD

**Issue by apennamen** [Connicpu/com-impl#1]
Hello,

First thanks a lot for this crate as it is currently helping me to [provide async support for queries in WMI](https://github.com/ohadravid/wmi-rs/pull/30)

I stumbled upon a problem called "too many Release call" or "not enough AddRef call" while using the crate, as you can see in [this stacktrace](https://github.com/ohadravid/wmi-rs/pull/30#issuecomment-758234236)

I think I found the reason behind this behavious is a missing call to AddRef in the QueryInterface implementation provided here:
https://github.com/Connicpu/com-impl/blob/master/derive-com-impl/src/derive.rs#L125

As describe in the MS documentation, there should be a call to AddRef before releasing the pointer :
https://docs.microsoft.com/en-us/windows/win32/api/unknwn/nf-unknwn-iunknown-queryinterface(refiid_void)

Regards,
AP

**Comment by Shnatsel** [comment]
Could also you publish a new release with the fix to crates.io?

Since this is a memory safety issue, it may have security implications. [RustSec](https://rustsec.org/) will release a [security advisory](https://github.com/RustSec/advisory-db/pull/649) once a release with the fix is up, so that affected users could detect the issue and upgrade. It will be surfaced via [cargo-audit](https://github.com/RustSec/cargo-audit) and [cargo-deny](https://github.com/EmbarkStudios/cargo-deny).

**Comment by Shnatsel** [comment]
Also, thank you for the swift fix!
